num1 = int(input("Enter 1st positive integer: "))
num2 = int(input("Enter 2nd positive integer: "))

print("Math operations:")
print(f"Add: {num1} + {num2} = {num1 + num2}")
print(f"Minus: {num1} - {num2} = {num1 - num2}")
print(f"Times: {num1} * {num2} = {num1 * num2}")
print(f"Modulo: {num1} % {num2} = {num1 % num2}")
print(f"Division: {num1} / {num2} = {num1 / num2}")
print(f"Floor division: {num1} // {num2} = {num1 // num2}")